### ISSUE TITLE
You can't delete bed recipes by doing this in the GTM addon (using IGTAddon)

### ISSUE THREAD

**Issue by Exzept1on** [GregTechCEu/GregTechCEu-1.19#1352]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer, Multiplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

TFC, KubeJS.

### Expected Behavior

Bed recipes are being deleted.

### Actual Behavior

Bed recipes are not deleted.

### Steps to Reproduce

1. Create own addon for GTM (with class which extends IGTAddon).
2. In class which IGTAddon try to use removeRecipes method.
3. Enable hardWoodRecipes. (I'm not sure if it affects)
4. Just type in `removeRecipes` section something like that `consumer.accept(new ResourceLocation("gtceu", "shaped/white_bed"));` or `consumer.accept(new ResourceLocation("gtceu:shaped/white_bed"));` 
5. Nothing happens.

### Additional Information

I'm not sure if this can happen with other recipes. but so far I'm having problems with the bed recipes that GTM adds.

**Comment by screret** [comment]
I'll assume this is fixed now that the GT recipe filter has been added.

**Comment by Exzept1on** [comment]
Tested now with GT 1.3.0, issue still exists, reopen this pls

The same thing can be done directly in GTCEu by simply adding the lines that I described above in the `recipeRemoval` method, as well as bed recipes will not be deleted.

**Comment by screret** [comment]
> Tested now with GT 1.3.0, issue still exists, reopen this pls
> 
> The same thing can be done directly in GTCEu by simply adding the lines that I described above in the `recipeRemoval` method, as well as bed recipes will not be deleted.

try the build in #1418?

**Comment by Exzept1on** [comment]
Yep, with this build works fine, thanks for fix
