### ISSUE TITLE
Large performance loss from 1.4.1 -> 1.4.2

### ISSUE THREAD

**Issue by Fuyukai** [GregTechCEu/GregTechCEu-1.19#2018]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

ssp

### Cross-Mod Interaction

No

### Other Installed Mods

too many to list here + largely not relevant. check the spark profiles list

### Expected Behavior

- Not to lose 5ms per tick

### Actual Behavior

- Lost 5ms per tick 

### Steps to Reproduce

1) load the game
2) press F3
3) notice that integrated server tick time is way higher

### Additional Information

Slow (1.4.2) spark profile: https://files.catbox.moe/sp40na.sparkprofile

Fast-ish (1.4.1) spark profile: https://files.catbox.moe/81sb8o.sparkprofile

The slower profile now spends significantly more time in RecipeLogic#findAndHandle.

**Comment by krossgg** [comment]
Hi, please reattach the profile for 1.4.2, I can't get it to load. Thanks.

**Comment by Fuyukai** [comment]
Here's a second 1.4.2 profile: https://files.catbox.moe/s7ss07.sparkprofile

**Comment by screret** [comment]
could you run one with a `--only-ticks-over 50` in the command parameters?

**Comment by screret** [comment]
so we actually see what's the laggy part

**Comment by Fuyukai** [comment]
Web viewer works this time: https://spark.lucko.me/1ogovtM3kR. Seems to be generators.

**Comment by krossgg** [comment]
Hi, could you try with the `gtceu-1.20.1-1.4.3.jar` file found in this zip and let us know? Thanks. It looks like a problem that _may_ have already been fixed in a PR but it hasn't made its way to release yet.

https://github.com/GregTechCEu/GregTech-Modern/actions/runs/11016580412/artifacts/1972244733

**Comment by Fuyukai** [comment]
This doesn't fix anything, sadly. [Regular profile](https://spark.lucko.me/Mfbxg2YmQe) and [50ms profile](https://spark.lucko.me/yKZTi9WgT4) still show the same slowdown.

**Comment by Fuyukai** [comment]
Git bisect shows that the commit that introduced the regression was 05f5dd120c959e192a92ba73210b994c15ad4102, or PR #1955.
