### ISSUE TITLE
[Crash] Couldn't find registry entry for ResourceKey[minecraft:worldgen/placed_feature / gtceu:rubber_tree]

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#247]
### GregTech CEu Version

1.20.1-1.0.9

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

No crash.

### Actual Behavior

Crash when entering or creating world.

### Steps to Reproduce

1. Enter an existing world or create a new world.
2. Crash.

### Additional Information

[crash-2023-08-01_19.10.14-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12228408/crash-2023-08-01_19.10.14-client.txt)
[crash-2023-08-01_19.12.04-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12228409/crash-2023-08-01_19.12.04-client.txt)

**Comment by Phoupraw** [comment]
The two crash reports above are in development enviroment. The following is in produce enviroment.
[minecraft-exported-crash-info-2023-08-01T22-07-17.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12230093/minecraft-exported-crash-info-2023-08-01T22-07-17.zip)

**Comment by Yefancy** [comment]
the latest commit?

**Comment by Phoupraw** [comment]
> the latest commit?

The latest version from modrinth, not the latest commit in the github.

**Comment by screret** [comment]
this is fixed in dev

**Comment by Yefancy** [comment]
#225
#238

**Comment by Phoupraw** [comment]
This crash still happens.
[minecraft-exported-crash-info-2023-08-06T12-05-57.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12268679/minecraft-exported-crash-info-2023-08-06T12-05-57.zip)
[minecraft-exported-crash-info-2023-08-06T02-14-02.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12268680/minecraft-exported-crash-info-2023-08-06T02-14-02.zip)
[minecraft-exported-crash-info-2023-08-06T18-23-49.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12269165/minecraft-exported-crash-info-2023-08-06T18-23-49.zip)
