### ISSUE TITLE
EMI Recipe Tree renders numbers behind some items

### ISSUE THREAD

**Issue by jtuc** [GregTechCEu/GregTechCEu-1.19#2735]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

039659fb5a4ac25685575f3793db1e507e971a5b and newer (i.e. 1.6.0+)

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

EMI

### Expected Behavior

![2025-01-12_20 06 30](https://github.com/user-attachments/assets/041332c0-dbf2-413f-a681-cd4d812af2a8)

### Actual Behavior

![2025-01-12_19 53 09](https://github.com/user-attachments/assets/c94c08e4-141c-4430-a529-3e2cce13413d)

### Steps to Reproduce

Open EMI
View the recipe tree of e.g. the Lapotronic Energy Orb

### Additional Information

I ran a git bisect; this was introduced as part of 039659fb5a4ac25685575f3793db1e507e971a5b.

**Comment by jtuc** [comment]
Out of curiosity, I also tested the yo/ui branch (6cbed2f9407d217817770c9d14547413f47211a2)
In this branch, the numbers are still rendered behind icons in the tree itself, but are rendered correctly in the Total Cost/Leftovers sections.
![2025-01-13_12 40 14](https://github.com/user-attachments/assets/6f57ef1f-6e6b-4bb0-9198-52592eb559e6)

**Comment by jtuc** [comment]
Workaround: Disabling "Batched Rendering" in EMI causes the tree to render correctly.

**Comment by omergunr100** [comment]
Should be fixed when Low-Drag-MC/LDLib-MultiLoader#61 is merged

**Comment by Cosmoros-git** [comment]
> Should be fixed when [Low-Drag-MC/LDLib-MultiLoader#61](https://github.com/Low-Drag-MC/LDLib-MultiLoader/pull/61) is merged

The latest version of the Low Drag lib still appears to have the same issue still. 1.0.34

![Image](https://github.com/user-attachments/assets/30930b0f-eb16-4afa-a25a-4f7986b7d688)

**Comment by omergunr100** [comment]
disable batched rendering for now and it'll probably work, still weird though.

**Comment by Pumpkin7266** [comment]
works on latest snapshot/EMI

<img width="425" height="405" alt="Image" src="https://github.com/user-attachments/assets/dbff43bd-79fc-4bd4-ab52-ded0c7da0da3" />
