### ISSUE TITLE
Unable to start the “Youer” server

### ISSUE THREAD

**Issue by nnn950711** [GregTechCEu/GregTechCEu-1.19#3555]
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

v7.0.2

### Minecraft Version

1.21.1 NeoForge

### Recipe Viewer Installed

None

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

gtceu-1.21.1-7.0.2
configuration-neoforge-1.21.1-3.1.1

### Expected Behavior

normal startup

### Actual Behavior

Unable to start

### Steps to Reproduce

Start the server

### Additional Information

Using “Youer” server Build 836409e2

[crash-2025-07-27_12.26.37-fml.txt](https://github.com/user-attachments/files/21451779/crash-2025-07-27_12.26.37-fml.txt)

[latest.log](https://github.com/user-attachments/files/21451780/latest.log)

[debug.log](https://github.com/user-attachments/files/21451781/debug.log)

**Comment by screret** [comment]
Fixed in #3542

**Comment by nnn950711** [comment]
> Fixed in [#3542](https://github.com/GregTechCEu/GregTech-Modern/pull/3542)

I tried downloading the new build from Actions, but it still crashed. This time, it seems to be a new problem.


[latest.log](https://github.com/user-attachments/files/21452540/latest.log)

[debug.log](https://github.com/user-attachments/files/21452541/debug.log)
