### ISSUE TITLE
hotbar items turns transparent while holding gt items, caused by ImmediatelyFast 

### ISSUE THREAD

**Issue by H2GamingTW** [GregTechCEu/GregTechCEu-1.19#503]
### GregTech CEu Version

GregTechCEu 1.20.1-1.0.13.e-forge

### Recipe Viewer Installed

No Recipe Viewer

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

hotbar items to be displayed normally

### Actual Behavior

items turns transparant

### Steps to Reproduce

install gt with immediately fast

**Comment by screret** [comment]
assuming this is now fixed by us using JSON for item models.

**Comment by Akoto090** [comment]
Bug does still exist


Forge 47.3.1 or Neoforge 47.1.106
Installed mods:
- ImmediatelyFast 1.2.18
- GregTech 1.20.1-1.3.0

[Bildschirmaufzeichnung vom 2024-06-14 03-44-18.webm](https://github.com/GregTechCEu/GregTech-Modern/assets/101405799/62a69f79-2118-4644-b1ab-77b7c07d0f70)

**Comment by Akoto090** [comment]
disabling gui batching in ImmediatelyFast config fixed it

**Comment by Deepacat** [comment]
lol disabling that option fixed something else for me before
